app = "serena-relay"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  PORT = "8080"
  UPSTREAM_URL = "https://serena-mcp.fly.dev"
  SERVICE_NAME = "serena"
  LOG_LEVEL = "INFO"
